import { z } from 'zod'
import Doctor, { appointmentMethods } from '../models/Doctor.js'
import Clinic from '../models/Clinic.js'
import Hospital from '../models/Hospital.js'
import Location from '../models/Location.js'
import Speciality from '../models/Speciality.js'
import AppError from '../utils/AppError.js'
import { removeDoctorImage, saveDoctorImage } from '../services/doctorImageStorage.js'

const objectId = z.string().regex(/^[a-f\d]{24}$/i)
const time = z.string().regex(/^\d{2}:\d{2}$/)
const schedule = z.array(z.object({ day: z.enum(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']), isAvailable: z.boolean(), slots: z.array(z.object({ startTime: time, endTime: time })).max(8), notes: z.string().max(160).optional() })).max(7)
const practiceFields = { appointmentMethods: z.array(z.enum(appointmentMethods)).min(1).max(appointmentMethods.length), schedule, department: z.string().trim().max(120).optional(), consultationFee: z.number().min(0).max(100000).optional(), notes: z.string().trim().max(200).optional() }
const doctorInput = z.object({ fullName: z.string().trim().min(3).max(140), slug: z.string().regex(/^[a-z0-9-]+$/), primaryLocation: objectId, primarySpeciality: objectId, qualifications: z.array(z.string().trim().min(2).max(160)).max(12).default([]), yearsOfExperience: z.number().int().min(0).max(80).optional(), languages: z.array(z.string().trim().min(2).max(50)).max(12).default([]), bio: z.string().trim().max(1500).optional(), verification: z.object({ status: z.enum(['PENDING', 'VERIFIED', 'NEEDS_REVIEW']), profileCompleteness: z.number().int().min(0).max(100) }).optional(), clinicPractices: z.array(z.object({ clinic: objectId, ...practiceFields })).max(8).default([]), hospitalPractices: z.array(z.object({ hospital: objectId, ...practiceFields })).max(8).default([]) }).strict()
const escapeRegex = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
export async function listAdminDoctors(request, response) { const search = typeof request.query.search === 'string' ? request.query.search.trim().slice(0, 80) : ''; const filter = search ? { fullName: { $regex: escapeRegex(search), $options: 'i' } } : {}; const doctors = await Doctor.find(filter).sort({ updatedAt: -1 }).populate('primaryLocation primarySpeciality').lean(); response.json({ data: doctors }) }
export async function doctorOptions(request, response) { const [locations, specialities, clinics, hospitals] = await Promise.all([Location.find().sort({ state: 1, city: 1 }).lean(), Speciality.find({ isActive: true }).sort({ name: 1 }).lean(), Clinic.find().populate('location').lean(), Hospital.find().populate('location').lean()]); response.json({ data: { locations, specialities, clinics, hospitals } }) }
export async function getAdminDoctor(request, response) { const doctor = await Doctor.findById(request.params.id).populate('primaryLocation primarySpeciality clinicPractices.clinic hospitalPractices.hospital'); if (!doctor) throw new AppError('Doctor not found.', 404); response.json({ data: doctor }) }
export async function createAdminDoctor(request, response) { const parsed = doctorInput.safeParse(request.body); if (!parsed.success) throw new AppError('Invalid doctor details.', 400, parsed.error.flatten().fieldErrors); const doctor = await Doctor.create({ ...parsed.data, isFictional: false }); response.status(201).json({ data: doctor }) }
export async function updateAdminDoctor(request, response) { const parsed = doctorInput.partial().safeParse(request.body); if (!parsed.success) throw new AppError('Invalid doctor details.', 400, parsed.error.flatten().fieldErrors); const doctor = await Doctor.findByIdAndUpdate(request.params.id, parsed.data, { new: true, runValidators: true }); if (!doctor) throw new AppError('Doctor not found.', 404); response.json({ data: doctor }) }
export async function toggleAdminDoctor(request, response) { const parsed = z.object({ isActive: z.boolean() }).safeParse(request.body); if (!parsed.success) throw new AppError('isActive must be true or false.', 400); const doctor = await Doctor.findByIdAndUpdate(request.params.id, parsed.data, { new: true }); if (!doctor) throw new AppError('Doctor not found.', 404); response.json({ data: doctor }) }
export async function uploadAdminDoctorImage(request, response) { const doctor = await Doctor.findById(request.params.id); if (!doctor) throw new AppError('Doctor not found.', 404); if (!request.file) throw new AppError('Select an image to upload.', 400); const previousUrl = doctor.profileImageUrl; const previousPublicId = doctor.profileImagePublicId; const uploaded = await saveDoctorImage(request.file); doctor.profileImageUrl = uploaded.profileImageUrl; doctor.profileImagePublicId = uploaded.profileImagePublicId; try { await doctor.save() } catch (error) { await removeDoctorImage(uploaded.profileImageUrl, uploaded.profileImagePublicId); throw error } if (previousUrl && previousUrl !== uploaded.profileImageUrl) removeDoctorImage(previousUrl, previousPublicId).catch(() => {}); response.status(201).json({ data: { profileImageUrl: doctor.profileImageUrl } }) }
