import { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import axios from 'axios'
import Logo from '../components/common/Logo'

const api = axios.create({ baseURL: import.meta.env.VITE_API_URL || 'http://localhost:5000/api', withCredentials: true })

export default function AdminVerifications() {
  const [doctors, setDoctors] = useState([])
  const [status, setStatus] = useState('')
  const [sources, setSources] = useState({})
  const [error, setError] = useState('')
  const navigate = useNavigate()
  const load = useCallback(() => api.get('/admin/verifications', { params: status ? { status } : {} }).then((response) => { setError(''); setDoctors(response.data.data); setSources(Object.fromEntries(response.data.data.map((doctor) => [doctor._id, (doctor.verification.sources || []).join(', ')]))) }).catch((requestError) => { if (requestError.response?.status === 401) navigate('/admin/login'); else { setDoctors([]); setError(requestError.response?.data?.error?.message || 'The verification queue could not be loaded. Please try again.') } }), [navigate, status])
  useEffect(() => { load() }, [load])
  async function update(doctor, nextStatus) { try { const sourceList = (sources[doctor._id] || '').split(',').map((source) => source.trim()).filter(Boolean); await api.patch(`/admin/verifications/${doctor._id}`, { status: nextStatus, sources: sourceList }); load() } catch (requestError) { setError(requestError.response?.data?.error?.message || 'The verification update could not be saved.') } }
  return <main className="min-h-screen bg-canvas px-5 py-8"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between"><Logo /><Link to="/admin" className="text-sm font-bold text-forest">Dashboard</Link></header><div className="mt-12"><p className="text-xs font-bold uppercase tracking-[.14em] text-forest">Information review</p><h1 className="mt-2 font-display text-5xl text-ink">Verification queue</h1><p className="mt-3 text-muted">Verification communicates the review status of listed profile details; it is not a measure of medical quality.</p></div><label className="mt-8 inline-grid gap-1 text-sm font-bold">Status<select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-line p-3 font-normal"><option value="">Pending and needs review</option><option value="PENDING">Pending</option><option value="NEEDS_REVIEW">Needs review</option><option value="VERIFIED">Verified</option></select></label>{error && <p className="mt-4 text-coral">{error}</p>}<div className="mt-8 grid gap-4">{doctors.map((doctor) => <article key={doctor._id} className="rounded-2xl border border-line bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-forest">{doctor.verification.status.replace('_', ' ')}</p><h2 className="mt-2 text-lg font-extrabold text-ink">{doctor.fullName}</h2><p className="mt-1 text-sm text-muted">{doctor.primarySpeciality?.name} · {doctor.primaryLocation?.city}</p></div><select value={doctor.verification.status} onChange={(event) => update(doctor, event.target.value)} className="rounded-xl border border-line p-3 text-sm"><option value="PENDING">Pending</option><option value="VERIFIED">Verified</option><option value="NEEDS_REVIEW">Needs review</option></select></div><label className="mt-4 grid gap-2 text-sm font-bold">Sources checked (comma separated)<input value={sources[doctor._id] || ''} onChange={(event) => setSources((current) => ({ ...current, [doctor._id]: event.target.value }))} placeholder="Official clinic page, direct practice confirmation" className="rounded-xl border border-line p-3 font-normal" /></label><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted">Last verified: {doctor.verification.lastVerifiedAt ? new Date(doctor.verification.lastVerifiedAt).toLocaleDateString() : 'Not yet verified'}</p><button type="button" onClick={() => update(doctor, doctor.verification.status)} className="rounded-full border border-ink px-4 py-2 text-sm font-bold text-ink">Save verification</button></div></article>)}{!doctors.length && <p className="rounded-2xl border border-line bg-white p-6 text-sm text-muted">No profiles in this queue.</p>}</div></div></main>
}
