import { Filter, SlidersHorizontal } from 'lucide-react'

function ResultControls({ filters, onChange, onClear }) {
  const fields = <><label className="text-sm font-semibold text-ink">Sort <select value={filters.sort} onChange={(event) => onChange({ sort: event.target.value })} className="ml-2 rounded-lg border border-line bg-white px-2 py-2 text-sm font-medium outline-none focus:border-forest"><option value="popular">Popular</option><option value="experience">Most experienced</option><option value="verified">Recently verified</option><option value="name">Name A–Z</option></select></label><label className="text-sm font-semibold text-ink">Appointment <select value={filters.appointment} onChange={(event) => onChange({ appointment: event.target.value })} className="ml-2 rounded-lg border border-line bg-white px-2 py-2 text-sm font-medium outline-none focus:border-forest"><option value="">Any</option><option value="PHONE_BOOKING">Phone booking</option><option value="WALK_IN">Walk-ins</option><option value="ONLINE_BOOKING">Online booking</option></select></label><label className="inline-flex items-center gap-2 text-sm font-semibold text-ink"><input type="checkbox" checked={filters.verifiedOnly} onChange={(event) => onChange({ verifiedOnly: event.target.checked })} className="size-4 accent-[#1768d8]" /> Verified only</label></>
  return (
    <div className="mt-8 border-y border-line py-4"><div className="hidden flex-wrap items-center justify-between gap-4 lg:flex"><div className="flex items-center gap-2 text-sm font-bold text-ink"><SlidersHorizontal size={17} aria-hidden="true" /> Refine results</div><div className="flex flex-wrap items-center gap-4">{fields}<button type="button" onClick={onClear} className="text-sm font-bold text-forest hover:text-ink">Clear filters</button></div></div><details className="lg:hidden"><summary className="flex cursor-pointer list-none items-center justify-between text-sm font-bold text-ink"><span className="flex items-center gap-2"><Filter size={17} aria-hidden="true" /> Filters and sorting</span><span className="text-forest">Open</span></summary><div className="mt-4 grid gap-4">{fields}<button type="button" onClick={onClear} className="w-fit text-sm font-bold text-forest">Clear filters</button></div></details></div>
  )
}

export default ResultControls
